// Auto-generated by Payload during `next dev` / `next build`.
// Do not edit manually — any custom admin components must be registered
// in payload.config.ts and will appear here after the next build.

export const importMap = {};
